In [53]:
import pandas as pd

In [54]:
df=pd.read_csv("financial_dataset.csv")

In [55]:
df #Filter, sort, group, and summarize financial transactions. Generate sales reports, customer summaries
#, and Pivot Table-style analysis using Pandas to evaluate business performance.

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [56]:
df.head(2)

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00

In [57]:
df.tail(3)

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [58]:
df.shape

(2000, 10)

In [59]:
df["Transaction_Date"]=pd.to_datetime(df["Transaction_ID"],errors="coerce")
df.dtypes

Transaction_ID               int64
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status              object
City                        object
Transaction_Date    datetime64[ns]
dtype: object

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    2000 non-null   int64
 1   Customer_ID       2000 non-null   object
 2   Customer_Name     2000 non-null   object
 3   Category          1977 non-null   object
 4   Sales             1967 non-null   float64
 5   Profit            1970 non-null   float64
 6   Quantity          2000 non-null   int64
 7   Payment_Status    2000 non-null   object
 8   City              1979 non-null   object
 9   Transaction_Date  2000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 156.4+ KB

In [61]:
df.describe()

,Transaction_ID,Sales,Profit,Quantity,Transaction_Date
count,2000.000000,1967.000000,1970.000000,2000.00000,2000
mean,11001.443500,25147.046263,3469.098985,10.18850,1970-01-01 00:00:00.000011001
min,10001.000000,516.000000,-4982.000000,1.00000,1970-01-01 00:00:00.000010001
25%,10502.750000,12723.500000,-812.500000,5.00000,1970-01-01 00:00:00.000010502
50%,10998.500000,25200.000000,3526.000000,10.00000,1970-01-01 00:00:00.000010998
75%,11504.250000,37545.000000,7711.250000,15.00000,1970-01-01 00:00:00.000011504
max,12000.000000,49923.000000,11988.000000,19.00000,1970-01-01 00:00:00.000012
std,578.772536,14375.624741,4923.386360,5.52958,NaN

In [62]:
df[df["City"]=="Mangalore"].head(5)

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
17,10351,CUST1298,Priya,Clothing,15586.0,6991.0,1,Paid,Mangalore,1970-01-01 00:00:00.000010351
25,11316,CUST1335,Neha,Stationery,38282.0,7098.0,16,Unpaid,Mangalore,1970-01-01 00:00:00.000011316
28,11492,CUST1303,Priya,Electronics,37856.0,3424.0,5,Paid,Mangalore,1970-01-01 00:00:00.000011492
42,10271,CUST1387,Anjali,Furniture,11456.0,-4011.0,7,Unpaid,Mangalore,1970-01-01 00:00:00.000010271
44,10353,CUST1263,Priya,Food,27542.0,-1849.0,17,Unpaid,Mangalore,1970-01-01 00:00:00.000010353

In [63]:
df[(df["Profit"]>7000) & (df["Payment_Status"]=="Paid")]

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,1970-01-01 00:00:00.000011001
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,1970-01-01 00:00:00.000010530
11,11576,CUST1313,Rahul,Electronics,30522.0,10540.0,18,Paid,Bangalore,1970-01-01 00:00:00.000011576
48,11423,CUST1237,Anjali,Clothing,27723.0,7270.0,8,Paid,Kochi,1970-01-01 00:00:00.000011423
52,10057,CUST1485,Rahul,Food,36703.0,11684.0,14,Paid,Chennai,1970-01-01 00:00:00.000010057
...,...,...,...,...,...,...,...,...,...,...
1964,10092,CUST1260,Rahul,Furniture,10440.0,10732.0,9,Paid,Chennai,1970-01-01 00:00:00.000010092
1971,10014,CUST1459,Rohan,Electronics,3629.0,10323.0,10,Paid,Chennai,1970-01-01 00:00:00.000010014
1979,10647,CUST1446,Neha,Stationery,25035.0,8937.0,11,Paid,Kochi,1970-01-01 00:00:00.000010647
1982,11155,CUST1061,Arun,Stationery,6006.0,7171.0,16,Paid,Kochi,1970-01-01 00:00:00.000011155
1983,11529,CUST1302,Rahul,Food,31686.0,7726.0,17,Paid,Kochi,1970-01-01 00:00:00.000011529

In [64]:
df[(df["City"]=="Mangalore") & (df["Payment_Status"]=="Pending")]

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
62,11898,CUST1446,Neha,Stationery,41264.0,-4945.0,5,Pending,Mangalore,1970-01-01 00:00:00.000011898
75,11952,CUST1464,Rahul,Food,21618.0,11142.0,13,Pending,Mangalore,1970-01-01 00:00:00.000011952
79,11495,CUST1216,Vivek,Stationery,30829.0,8322.0,1,Pending,Mangalore,1970-01-01 00:00:00.000011495
103,10100,CUST1202,Vivek,Food,24984.0,9900.0,13,Pending,Mangalore,1970-01-01 00:00:00.000010100
109,10112,CUST1296,Priya,Food,28296.0,-3828.0,9,Pending,Mangalore,1970-01-01 00:00:00.000010112
...,...,...,...,...,...,...,...,...,...,...
1938,10202,CUST1237,Priya,Stationery,42729.0,-2377.0,11,Pending,Mangalore,1970-01-01 00:00:00.000010202
1958,10776,CUST1368,Vivek,Stationery,29335.0,5464.0,9,Pending,Mangalore,1970-01-01 00:00:00.000010776
1963,11391,CUST1376,Sneha,Food,31107.0,609.0,4,Pending,Mangalore,1970-01-01 00:00:00.000011391
1988,10563,CUST1444,Sneha,FOOD,16472.0,11892.0,5,Pending,Mangalore,1970-01-01 00:00:00.000010563
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,1970-01-01 00:00:00.000011706

In [65]:
df.sort_values("Sales")

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
69,10549,CUST1063,Neha,Stationery,516.0,-4882.0,11,Pending,Kochi,1970-01-01 00:00:00.000010549
1945,11846,CUST1237,Rohan,Electronics,560.0,257.0,5,Unpaid,Chennai,1970-01-01 00:00:00.000011846
888,11457,CUST1179,Sneha,Stationery,566.0,9772.0,2,Unpaid,Delhi,1970-01-01 00:00:00.000011457
1869,11763,CUST1234,Vivek,Clothing,645.0,-3637.0,4,Unpaid,Chennai,1970-01-01 00:00:00.000011763
1192,11482,CUST1322,Priya,Stationery,678.0,-4596.0,6,Paid,Mumbai,1970-01-01 00:00:00.000011482
...,...,...,...,...,...,...,...,...,...,...
1780,11292,CUST1350,Rohan,Stationery,NaN,7886.0,7,Paid,Bangalore,1970-01-01 00:00:00.000011292
1803,11769,CUST1020,Sneha,Clothing,NaN,9688.0,2,Pending,Mumbai,1970-01-01 00:00:00.000011769
1822,10796,CUST1339,Vivek,Stationery,NaN,-4934.0,1,Unpaid,Chennai,1970-01-01 00:00:00.000010796
1885,10201,CUST1231,Priya,Furniture,NaN,3534.0,17,Unpaid,Chennai,1970-01-01 00:00:00.000010201
1949,11414,CUST1165,Arun,Electronics,NaN,9195.0,7,Paid,Kochi,1970-01-01 00:00:00.000011414

In [66]:
df.sort_values("Profit")

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1152,10138,CUST1472,Vivek,Furniture,27823.0,-4982.0,10,Paid,Kochi,1970-01-01 00:00:00.000010138
1891,11514,CUST1282,Rahul,Furniture,1393.0,-4979.0,7,Paid,Kochi,1970-01-01 00:00:00.000011514
527,11084,CUST1435,Sneha,Clothing,38744.0,-4972.0,5,Pending,Chennai,1970-01-01 00:00:00.000011084
1924,10720,CUST1215,Priya,Furniture,43669.0,-4952.0,6,Unpaid,Bangalore,1970-01-01 00:00:00.000010720
62,11898,CUST1446,Neha,Stationery,41264.0,-4945.0,5,Pending,Mangalore,1970-01-01 00:00:00.000011898
...,...,...,...,...,...,...,...,...,...,...
1686,10208,CUST1160,Sneha,Clothing,46540.0,NaN,16,Paid,Mumbai,1970-01-01 00:00:00.000010208
1703,11929,CUST1101,Neha,Electronics,30935.0,NaN,13,Unpaid,Kochi,1970-01-01 00:00:00.000011929
1834,10525,CUST1391,Anjali,Food,25506.0,NaN,16,Pending,Mumbai,1970-01-01 00:00:00.000010525
1961,11479,CUST1254,Anjali,Clothing,14298.0,NaN,3,Pending,Mumbai,1970-01-01 00:00:00.000011479
1984,10832,CUST1442,Rahul,Stationery,14752.0,NaN,7,Pending,Kochi,1970-01-01 00:00:00.000010832

In [69]:
Sales_report=df.groupby("Category").agg(
    total_revenue=("Sales","sum"),
    total_profit=("Profit","sum"),
)
Sales_report

             total_revenue  total_profit
Category
Clothing         9844177.0     1374186.0
Electronics      8390788.0     1104818.0
FOOD              420537.0       44420.0
Food             9751908.0     1344231.0
Furniture       10214137.0     1342336.0
Stationery       9547483.0     1416727.0
food              718585.0      121393.0

In [70]:
customer_summaries=df.groupby(["Customer_ID","Customer_Name"]).agg(
    Total_sales=("Sales","sum"),
    net_profit=("Profit","sum"),
    total_transaction=("Transaction_ID","count"),
    avg_iteams=("Quantity","mean"),
)
customer_summaries

                           Total_sales  net_profit  total_transaction  \
Customer_ID Customer_Name
CUST1001    Anjali             26279.0      3174.0                  2
            Priya              92702.0      3726.0                  3
            Rohan              27651.0      4867.0                  1
            Sneha              76707.0     13469.0                  2
CUST1002    Anjali             42074.0     -3993.0                  1
...                                ...         ...                ...
CUST1499    Rohan              61949.0     -6042.0                  2
CUST1500    Anjali             12272.0      3998.0                  1
            Priya              28729.0     10369.0                  1
            Rohan              65878.0      3108.0                  2
            Sneha              59021.0      8570.0                  3

                           avg_iteams
Customer_ID Customer_Name
CUST1001    Anjali           2.000000
            Priya           11.333333
            Rohan            8.000000
            Sneha           11.500000
CUST1002    Anjali           4.000000
...                               ...
CUST1499    Rohan           12.000000
CUST1500    Anjali          19.000000
            Priya           11.000000
            Rohan           12.000000
            Sneha           15.000000

[1537 rows x 4 columns]

In [74]:
pd.pivot_table(
    df,
    values="Profit",
    index="City",
    columns="Category",
    aggfunc="sum",
    fill_value=0.0,
)

Category,Clothing,Electronics,FOOD,Food,Furniture,Stationery,food
City,,,,,,,
Bangalore,282295.0,172666.0,7184.0,184445.0,199066.0,269748.0,23835.0
Chennai,195850.0,248529.0,4308.0,296867.0,199119.0,274224.0,42022.0
Delhi,231836.0,229418.0,13318.0,245670.0,219765.0,236584.0,10046.0
Kochi,156372.0,181375.0,-3221.0,201015.0,253415.0,230251.0,17577.0
Mangalore,301680.0,126549.0,11922.0,269682.0,200965.0,238515.0,19133.0
Mumbai,196887.0,124225.0,10909.0,144753.0,231247.0,168804.0,8780.0